import { Loader2, Save } from 'lucide-react';
import { useEffect, useState } from 'react';
import { AdminLayout } from '../components/layout/AdminLayout';
import { useAuth } from '../context/AuthContext';
import { supabase } from '../lib/supabase';

type Branding = { id?: string; platform_arabic_name: string; short_name: string; footer_text: string; main_brand_color: string };
type Content = { id: string; section_key: string; title_ar: string; body_ar: string; cta_label_ar: string; is_enabled: boolean };
const initialBranding: Branding = { platform_arabic_name: '', short_name: '', footer_text: '', main_brand_color: '#0d9f87' };

export const SettingsPage = ({ mode }: { mode: 'branding' | 'content' }) => {
  const { user } = useAuth(); const [branding, setBranding] = useState(initialBranding); const [content, setContent] = useState<Content[]>([]); const [busy, setBusy] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { let active = true; const load = async () => { const [brandResult, contentResult] = await Promise.all([supabase.from('branding_settings').select('id, platform_arabic_name, short_name, footer_text, main_brand_color').maybeSingle(), supabase.from('content_settings').select('id, section_key, title_ar, body_ar, cta_label_ar, is_enabled').order('sort_order')]); if (!active) return; if (brandResult.error || contentResult.error) setError(brandResult.error?.message || contentResult.error?.message || 'تعذر تحميل الإعدادات.'); else { if (brandResult.data) setBranding(brandResult.data as Branding); setContent((contentResult.data || []) as Content[]); } setBusy(false); }; void load(); return () => { active = false; }; }, []);
  const saveBranding = async () => { if (!user) return; setSaving(true); setMessage(null); setError(null); const payload = { platform_arabic_name: branding.platform_arabic_name, short_name: branding.short_name, footer_text: branding.footer_text, main_brand_color: branding.main_brand_color, updated_by: user.id }; const result = branding.id ? await supabase.from('branding_settings').update(payload).eq('id', branding.id) : await supabase.from('branding_settings').insert(payload); if (result.error) setError(result.error.message); else setMessage('تم حفظ الهوية في Supabase.'); setSaving(false); };
  const saveContent = async () => { if (!user) return; setSaving(true); setMessage(null); setError(null); for (const item of content) { const result = await supabase.from('content_settings').update({ title_ar: item.title_ar, body_ar: item.body_ar, cta_label_ar: item.cta_label_ar, is_enabled: item.is_enabled, updated_by: user.id }).eq('id', item.id); if (result.error) { setError(result.error.message); setSaving(false); return; } } setMessage('تم حفظ المحتوى في Supabase.'); setSaving(false); };
  return <AdminLayout><section className="admin-panel settings-panel"><h1>{mode === 'branding' ? 'الهوية والمحتوى' : 'إعدادات المنصة'}</h1><p className="settings-note">هذه القيم تُقرأ وتُحفظ في الجداول الفعلية، وتخضع لصلاحيات الإدارة.</p>{busy ? <div className="empty-panel"><Loader2 className="animate-spin" /> جارٍ التحميل…</div> : error ? <div className="empty-panel text-red-600">{error}</div> : mode === 'branding' ? <><label>اسم المنصة<input value={branding.platform_arabic_name} onChange={(event) => setBranding({ ...branding, platform_arabic_name: event.target.value })} /></label><label>الاسم المختصر<input value={branding.short_name} onChange={(event) => setBranding({ ...branding, short_name: event.target.value })} /></label><label>نص التذييل<textarea value={branding.footer_text} onChange={(event) => setBranding({ ...branding, footer_text: event.target.value })} /></label><label>اللون الرئيسي<input type="color" value={branding.main_brand_color} onChange={(event) => setBranding({ ...branding, main_brand_color: event.target.value })} /></label><button className="dashboard-action" onClick={() => void saveBranding()} disabled={saving}><Save size={16} /> حفظ الهوية</button></> : <>{content.length === 0 ? <div className="empty-panel">لا توجد أقسام محتوى محفوظة حالياً.</div> : content.map((item, index) => <fieldset key={item.id}><legend>{item.section_key}</legend><input value={item.title_ar} onChange={(event) => setContent(content.map((current, currentIndex) => currentIndex === index ? { ...current, title_ar: event.target.value } : current))} /><textarea value={item.body_ar} onChange={(event) => setContent(content.map((current, currentIndex) => currentIndex === index ? { ...current, body_ar: event.target.value } : current))} /><label><input type="checkbox" checked={item.is_enabled} onChange={(event) => setContent(content.map((current, currentIndex) => currentIndex === index ? { ...current, is_enabled: event.target.checked } : current))} /> مفعل</label></fieldset>)}<button className="dashboard-action" onClick={() => void saveContent()} disabled={saving}><Save size={16} /> حفظ المحتوى</button></>}</section>{message && <p className="settings-success">{message}</p>}</AdminLayout>;
};
