import { Bell, CheckCircle2, ImagePlus, Loader2, Palette, Plus, Save, ShieldCheck, Tag, University, UserRound, WalletCards, X, XCircle } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { AdminLayout } from '../components/layout/AdminLayout';
import { useAuth } from '../context/AuthContext';
import { supabase } from '../lib/supabase';

type Branding = {
  id?: string; platform_arabic_name: string; platform_english_name: string; short_name: string; footer_text: string;
  site_description?: string | null; hero_image_url?: string | null; hero_title_ar?: string | null; hero_subtitle_ar?: string | null;
  main_brand_color: string; secondary_color?: string; accent_color?: string; contact_phone?: string | null; whatsapp?: string | null; email?: string | null;
  logo_url?: string | null; dark_logo_url?: string | null; favicon_url?: string | null; customer_header_logo_url?: string | null; admin_sidebar_logo_url?: string | null;
};
type Content = { id: string; section_key: string; title_ar: string; body_ar: string; cta_label_ar: string; is_enabled: boolean };
type AdminRow = { profile_id: string; email: string | null; full_name: string; role: 'ADMIN' | 'SUPER_ADMIN' | 'STAFF'; status: string; created_at: string; last_sign_in_at: string | null; permissions: string[] };
const initialBranding: Branding = { platform_arabic_name: 'أسنان الأساس', platform_english_name: 'Asnas Al-Asas', short_name: 'الأساس', footer_text: '', main_brand_color: '#0d9f87', secondary_color: '#123d73', accent_color: '#12a895' };
const tabs = [['general', 'الإعدادات العامة وهوية الموقع', UserRound], ['images', 'الصور والشعارات', ImagePlus], ['whatsapp', 'واتساب الإدارة', WalletCards], ['categories', 'تصنيفات الحالات', Tag], ['universities', 'خيارات الجامعات', University], ['notifications', 'الإشعارات', Bell], ['theme', 'مظهر المنصة', Palette], ['permissions', 'إدارة المدراء والصلاحيات', ShieldCheck], ['about', 'حول المنصة', CheckCircle2]] as const;
const imageFields = [['logo_url', 'الشعار الرئيسي'], ['dark_logo_url', 'شعار الوضع الليلي'], ['favicon_url', 'أيقونة المتصفح'], ['customer_header_logo_url', 'شعار واجهة الزبون'], ['admin_sidebar_logo_url', 'شعار لوحة الإدارة'], ['hero_image_url', 'صورة Hero الرئيسية']] as const;
const permissionOptions = ['patients.manage', 'cases.manage', 'students.verify', 'matches.manage', 'appointments.manage', 'universities.manage', 'reports.view', 'settings.manage', 'branding.manage', 'users.manage'];

export const SettingsPage = ({ mode }: { mode: 'branding' | 'content' }) => {
  const { user, profile } = useAuth();
  const [branding, setBranding] = useState<Branding>(initialBranding); const [brandingColumns, setBrandingColumns] = useState<Set<string>>(new Set()); const [content, setContent] = useState<Content[]>([]); const [admins, setAdmins] = useState<AdminRow[]>([]);
  const [busy, setBusy] = useState(true); const [saving, setSaving] = useState(false); const [managerBusy, setManagerBusy] = useState(false); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  const [activeTab, setActiveTab] = useState(mode === 'content' ? 'about' : 'general'); const [showAddAdmin, setShowAddAdmin] = useState(false); const [managerEmail, setManagerEmail] = useState(''); const [managerRole, setManagerRole] = useState<'ADMIN' | 'STAFF'>('ADMIN'); const [managerPermissions, setManagerPermissions] = useState<string[]>([]);
  const active = useMemo(() => tabs.find(([key]) => key === activeTab) || tabs[0], [activeTab]);

  const loadManagers = async () => { const result = await supabase.rpc('admin_list_managers'); if (result.error) setError(`تعذر تحميل المدراء: ${result.error.message}`); else setAdmins((result.data || []) as AdminRow[]); };
  useEffect(() => { let mounted = true; (async () => { const [brand, copy] = await Promise.all([supabase.from('branding_settings').select('*').maybeSingle(), supabase.from('content_settings').select('id, section_key, title_ar, body_ar, cta_label_ar, is_enabled').order('sort_order')]); if (!mounted) return; if (brand.error || copy.error) setError(brand.error?.message || copy.error?.message || 'تعذر تحميل الإعدادات.'); else { if (brand.data) { setBranding({ ...initialBranding, ...(brand.data as Branding) }); setBrandingColumns(new Set(Object.keys(brand.data))); } setContent((copy.data || []) as Content[]); } await loadManagers(); if (mounted) setBusy(false); })(); return () => { mounted = false; }; }, []);

  const saveBranding = async () => { if (!user) return; setSaving(true); setMessage(null); setError(null); const payload: Record<string, unknown> = { platform_arabic_name: branding.platform_arabic_name, platform_english_name: branding.platform_english_name, short_name: branding.short_name, footer_text: branding.footer_text, main_brand_color: branding.main_brand_color, secondary_color: branding.secondary_color, accent_color: branding.accent_color, contact_phone: branding.contact_phone || null, whatsapp: branding.whatsapp || null, email: branding.email || null, logo_url: branding.logo_url || null, dark_logo_url: branding.dark_logo_url || null, favicon_url: branding.favicon_url || null, customer_header_logo_url: branding.customer_header_logo_url || null, admin_sidebar_logo_url: branding.admin_sidebar_logo_url || null, updated_by: user.id, updated_at: new Date().toISOString() }; for (const field of ['site_description', 'hero_image_url', 'hero_title_ar', 'hero_subtitle_ar']) if (brandingColumns.has(field)) payload[field] = branding[field as keyof Branding] ?? null; const query = branding.id ? supabase.from('branding_settings').update(payload).eq('id', branding.id) : supabase.from('branding_settings').insert(payload); const result = await query.select('*').single(); if (result.error) setError(result.error.message); else { setBranding({ ...initialBranding, ...(result.data as Branding) }); setBrandingColumns(new Set(Object.keys(result.data))); document.title = branding.platform_arabic_name || 'لوحة الإدارة'; setMessage('تم الحفظ والتحقق من القراءة من Supabase.'); } setSaving(false); };
  const saveContent = async () => { if (!user) return; setSaving(true); setMessage(null); setError(null); for (const item of content) { const result = await supabase.from('content_settings').update({ title_ar: item.title_ar, body_ar: item.body_ar, cta_label_ar: item.cta_label_ar, is_enabled: item.is_enabled, updated_by: user.id, updated_at: new Date().toISOString() }).eq('id', item.id).select('id').single(); if (result.error) { setError(result.error.message); setSaving(false); return; } } setMessage('تم حفظ المحتوى والتحقق من القراءة.'); setSaving(false); };
  const uploadImage = async (field: keyof Branding, file: File) => { const allowed = ['image/png', 'image/jpeg', 'image/webp', 'image/svg+xml']; if (!user || !allowed.includes(file.type)) { setError('اختر PNG أو JPEG أو WebP أو SVG فقط.'); return; } if (file.size > 5 * 1024 * 1024) { setError('الحد الأقصى للصورة 5MB.'); return; } setSaving(true); setError(null); const path = `branding/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g, '-')}`; const result = await supabase.storage.from('branding-assets').upload(path, file, { contentType: file.type, upsert: false }); if (result.error) setError(`تعذر الرفع: ${result.error.message}. تأكد من تطبيق Migration الخاصة بـ branding-assets.`); else { const { data } = supabase.storage.from('branding-assets').getPublicUrl(path); setBranding((current) => ({ ...current, [field]: `${data.publicUrl}?v=${Date.now()}` })); setMessage('تم رفع الملف ومعاينته. اضغط حفظ التغييرات لتثبيت المسار في الإعدادات.'); } setSaving(false); };
  const addManager = async () => { setManagerBusy(true); setError(null); const result = await supabase.rpc('admin_add_manager', { p_email: managerEmail.trim(), p_role: managerRole, p_permissions: managerPermissions }); if (result.error) setError(result.error.message); else { setMessage('تمت إضافة المدير وتسجيل العملية عبر RPC.'); setShowAddAdmin(false); setManagerEmail(''); await loadManagers(); } setManagerBusy(false); };
  const changeManagerStatus = async (row: AdminRow, status: 'VERIFIED' | 'SUSPENDED') => { setManagerBusy(true); setError(null); const result = await supabase.rpc('admin_update_manager', { p_profile_id: row.profile_id, p_role: row.role === 'STAFF' ? 'STAFF' : 'ADMIN', p_status: status, p_permissions: row.permissions || [] }); if (result.error) setError(result.error.message); else { setMessage('تم تحديث الحالة والتحقق من العملية.'); await loadManagers(); } setManagerBusy(false); };

  const brandingFields = <div className="settings-form-grid"><label>اسم الموقع بالعربية<input value={branding.platform_arabic_name} onChange={(e) => setBranding({ ...branding, platform_arabic_name: e.target.value })} /></label><label>اسم الموقع بالإنجليزية<input value={branding.platform_english_name} onChange={(e) => setBranding({ ...branding, platform_english_name: e.target.value })} /></label><label>الاسم المختصر<input value={branding.short_name} onChange={(e) => setBranding({ ...branding, short_name: e.target.value })} /></label>{activeTab === 'whatsapp' && <><label>رقم واتساب الإدارة<input inputMode="tel" value={branding.whatsapp || ''} onChange={(e) => setBranding({ ...branding, whatsapp: e.target.value })} /></label><label>هاتف الإدارة<input inputMode="tel" value={branding.contact_phone || ''} onChange={(e) => setBranding({ ...branding, contact_phone: e.target.value })} /></label><label>البريد الإلكتروني<input type="email" value={branding.email || ''} onChange={(e) => setBranding({ ...branding, email: e.target.value })} /></label></>}{activeTab === 'theme' && <><label>اللون الرئيسي<input type="color" value={branding.main_brand_color} onChange={(e) => setBranding({ ...branding, main_brand_color: e.target.value })} /></label><label>اللون الثانوي<input type="color" value={branding.secondary_color || '#123d73'} onChange={(e) => setBranding({ ...branding, secondary_color: e.target.value })} /></label><label>لون التمييز<input type="color" value={branding.accent_color || '#12a895'} onChange={(e) => setBranding({ ...branding, accent_color: e.target.value })} /></label></>}{activeTab === 'general' && <><label className="settings-wide-field">وصف الموقع<textarea value={branding.site_description || branding.footer_text} onChange={(e) => setBranding({ ...branding, site_description: e.target.value, footer_text: e.target.value })} /></label>{brandingColumns.has('hero_title_ar') && <label>العنوان الرئيسي<input value={branding.hero_title_ar || ''} onChange={(e) => setBranding({ ...branding, hero_title_ar: e.target.value })} /></label>}{brandingColumns.has('hero_subtitle_ar') && <label>النص التعريفي<textarea value={branding.hero_subtitle_ar || ''} onChange={(e) => setBranding({ ...branding, hero_subtitle_ar: e.target.value })} /></label>}{brandingColumns.has('hero_image_url') && <label>رابط صورة الواجهة<input type="url" value={branding.hero_image_url || ''} onChange={(e) => setBranding({ ...branding, hero_image_url: e.target.value })} /></label>}</>}</div>;
  const images = <><div className="settings-form-grid">{imageFields.map(([field, label]) => <label key={field}>{label}<input type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" onChange={(e) => { const file = e.target.files?.[0]; if (file) void uploadImage(field, file); }} />{branding[field] && <img className="settings-image-preview" src={String(branding[field])} alt={`معاينة ${label}`} />}</label>)}</div><p className="settings-note">الصور تُرفع من الجهاز إلى Bucket الهوية العام، وتُحفظ في Supabase بعد الضغط على حفظ التغييرات. لا تُستخدم صور المرضى أو الوثائق الطبية.</p></>;
  const managers = <><div className="management-toolbar"><div><b>المدراء الحاليون</b><small className="cell-subtitle">البيانات من Auth + profiles عبر RPC محمي.</small></div>{profile?.role === 'SUPER_ADMIN' && <button type="button" onClick={() => setShowAddAdmin(true)}><Plus size={15} /> إضافة مدير جديد</button>}</div><div className="table-scroll"><table><thead><tr><th>الاسم / البريد</th><th>الدور</th><th>الحالة</th><th>آخر دخول</th><th>الإجراء</th></tr></thead><tbody>{admins.map((row) => <tr key={row.profile_id}><td><b>{row.full_name}</b><small className="cell-subtitle">{row.email || 'بريد غير متاح'}</small></td><td>{row.role}</td><td>{row.status}</td><td>{row.last_sign_in_at ? new Date(row.last_sign_in_at).toLocaleString('ar-IQ') : 'غير متوفر'}</td><td>{row.status === 'SUSPENDED' ? <button className="row-action" disabled={managerBusy} onClick={() => void changeManagerStatus(row, 'VERIFIED')}>إعادة تفعيل</button> : <button className="row-action" disabled={managerBusy} onClick={() => void changeManagerStatus(row, 'SUSPENDED')}>تعطيل</button>}</td></tr>)}</tbody></table></div>{admins.length === 0 && <div className="empty-panel">لا توجد حسابات إدارة أو RPC غير مطبق.</div>}{showAddAdmin && <div className="modal-backdrop"><form className="admin-modal" onSubmit={(event) => { event.preventDefault(); void addManager(); }}><div className="panel-heading"><h2>إضافة مدير جديد</h2><button type="button" onClick={() => setShowAddAdmin(false)}><X size={18} /></button></div><label>بريد مستخدم Supabase Auth موجود<input type="email" required value={managerEmail} onChange={(e) => setManagerEmail(e.target.value)} /></label><label>الدور<select value={managerRole} onChange={(e) => setManagerRole(e.target.value as 'ADMIN' | 'STAFF')}><option value="ADMIN">Admin</option><option value="STAFF">Staff</option></select></label><fieldset><legend>الصلاحيات</legend>{permissionOptions.map((permission) => <label className="checkbox-row" key={permission}><input type="checkbox" checked={managerPermissions.includes(permission)} onChange={(e) => setManagerPermissions(e.target.checked ? [...managerPermissions, permission] : managerPermissions.filter((item) => item !== permission))} /> {permission}</label>)}</fieldset><div className="modal-actions"><button type="button" onClick={() => setShowAddAdmin(false)}>إلغاء</button><button className="dashboard-action" disabled={managerBusy}>{managerBusy ? <Loader2 className="animate-spin" size={16} /> : <Save size={16} />} تأكيد الإضافة</button></div></form></div>}</>;
  const renderedContent = content.length === 0 ? <div className="empty-panel">لا توجد أقسام محتوى محفوظة حالياً.</div> : <>{content.map((item, index) => <fieldset key={item.id}><legend>{item.section_key}</legend><input aria-label={`عنوان ${item.section_key}`} value={item.title_ar || ''} onChange={(e) => setContent(content.map((current, i) => i === index ? { ...current, title_ar: e.target.value } : current))} /><textarea aria-label={`نص ${item.section_key}`} value={item.body_ar || ''} onChange={(e) => setContent(content.map((current, i) => i === index ? { ...current, body_ar: e.target.value } : current))} /><label><input type="checkbox" checked={item.is_enabled} onChange={(e) => setContent(content.map((current, i) => i === index ? { ...current, is_enabled: e.target.checked } : current))} /> مفعل</label></fieldset>)}<button className="dashboard-action" onClick={() => void saveContent()} disabled={saving}><Save size={16} /> حفظ المحتوى</button></>;
  const unavailable = ['categories', 'notifications'].includes(activeTab); const body = activeTab === 'universities' ? <div className="admin-notice"><University size={20} /><span><b>إدارة الجامعات متاحة في قسم مستقل</b><small>يعرض القسم الجامعات الفعلية من Supabase ويستخدم مسار الحفظ المحكوم بـ RLS مع Readback بعد كل عملية.</small><Link className="dashboard-action" to="/universities">فتح إدارة الجامعات</Link></span></div> : unavailable ? <div className="settings-blocked"><ShieldCheck size={25} /><h3>القسم غير مفعّل</h3><p>لا يوجد مسار كتابة مثبت لهذا القسم في المخطط الحالي.</p></div> : activeTab === 'permissions' ? managers : activeTab === 'about' ? renderedContent : activeTab === 'images' ? <>{images}<button className="dashboard-action" onClick={() => void saveBranding()} disabled={saving}><Save size={16} /> حفظ التغييرات</button></> : <>{brandingFields}<button className="dashboard-action" onClick={() => void saveBranding()} disabled={saving}>{saving ? <Loader2 className="animate-spin" size={16} /> : <Save size={16} />} حفظ التغييرات</button></>;
  return <AdminLayout><div className="settings-heading"><div><span className="dashboard-eyebrow">الرئيسية / الإعدادات</span><h1>الإعدادات</h1><p>إدارة الهوية والمدراء من مصادر Supabase الفعلية.</p></div></div><div className="settings-layout"><nav className="settings-tabs" aria-label="أقسام الإعدادات">{tabs.map(([key, label, Icon]) => <button type="button" key={key} className={activeTab === key ? 'active' : ''} onClick={() => { setActiveTab(key); setMessage(null); setError(null); }}><Icon size={17} />{label}</button>)}</nav><section className="admin-panel settings-panel"><div className="settings-panel-heading"><div><h2>{active[1]}</h2><p className="settings-note">النجاح لا يظهر إلا بعد Readback أو نتيجة RPC ناجحة.</p></div>{message && <span className="settings-inline-success"><CheckCircle2 size={15} /> {message}</span>}</div>{busy ? <div className="empty-panel"><Loader2 className="animate-spin" /> جارٍ التحميل…</div> : error ? <div className="admin-error"><XCircle size={18} /><span>{error}</span></div> : body}</section></div></AdminLayout>;
};
