import { Activity, AlertCircle, CheckCircle, Loader2, MapPin, User } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link, Navigate } from 'react-router-dom';
import { Header } from '../../components/layout/Header';
import { useAuth } from '../../context/AuthContext';
import { supabase } from '../../lib/supabase';

type CaseRow = { id: string; case_number: string; patient_age: number | null; patient_gender: string | null; description: string; symptoms: string[] | null; ai_tags: string[] | null; ai_summary: string | null; created_at: string };
export const SearchCases = () => { const { user, loading } = useAuth(); const [cases, setCases] = useState<CaseRow[]>([]); const [busy, setBusy] = useState(true); const [error, setError] = useState<string | null>(null); useEffect(() => { if (!user) return; void supabase.rpc('search_anonymized_patient_cases', { p_limit: 30, p_offset: 0 }).then(({ data, error: queryError }) => { if (queryError) setError(queryError.message); else setCases((data || []) as CaseRow[]); setBusy(false); }); }, [user]); if (loading || busy) return <div className="min-h-screen grid place-items-center" dir="rtl"><Loader2 className="animate-spin text-primary-600" /></div>; if (!user) return <Navigate to="/login" replace />; return <div className="min-h-screen bg-gray-50" dir="rtl"><Header /><main className="mx-auto max-w-7xl px-4 py-10"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-center"><div><h1 className="text-3xl font-black text-slate-900">البحث عن الحالات</h1><p className="mt-2 text-slate-500">حالات مجهّلة وموافق عليها للمطابقة السريرية.</p></div><Link to="/student/request" className="rounded-xl bg-primary-600 px-5 py-3 text-center font-bold text-white">إنشاء طلب سريري</Link></div>{error && <p className="mt-7 flex gap-2 rounded-xl bg-red-50 p-4 text-sm text-red-700"><AlertCircle size={18} /> تعذر تحميل الحالات: {error}</p>}{!error && cases.length === 0 && <div className="mt-8 rounded-2xl bg-white p-10 text-center text-slate-500">لا توجد حالات منشورة للمطابقة حالياً.</div>}<div className="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{cases.map((patientCase) => <article key={patientCase.id} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-start justify-between gap-3"><span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-bold text-blue-700">{patientCase.case_number}</span><span className="flex items-center gap-1 rounded-lg bg-teal-50 px-2 py-1 text-xs font-bold text-teal-700"><CheckCircle size={14} /> متاحة</span></div><div className="mt-5 flex gap-4 text-sm text-slate-500"><span className="flex items-center gap-1"><User size={15} /> {patientCase.patient_age || '—'} سنة</span><span className="flex items-center gap-1"><MapPin size={15} /> محافظة محددة</span></div><h2 className="mt-5 text-lg font-black text-slate-800">حالة سريرية مجهّلة</h2><p className="mt-2 line-clamp-3 text-sm leading-7 text-slate-600">{patientCase.description}</p><div className="mt-4 flex flex-wrap gap-2">{(patientCase.symptoms || []).map((item) => <span key={item} className="rounded-md bg-slate-100 px-2 py-1 text-xs text-slate-600">{item}</span>)}{(patientCase.ai_tags || []).map((item) => <span key={item} className="flex items-center gap-1 rounded-md bg-primary-50 px-2 py-1 text-xs text-primary-700"><Activity size={12} />{item}</span>)}</div><button className="mt-6 w-full rounded-xl border border-primary-600 py-2.5 font-bold text-primary-700">طلب الحالة</button></article>)}</div></main></div>; };
